# Change these first
owner: andrewgioia # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Gioia Cloud
    url: https://gioia.cloud
  - name: Gioia Social
    url: https://gioia.social/api/v2/instance
  - name: Gioia Photos
    url: https://gioia.photos
  - name: Gioia Chat
    url: https://element.gioia.chat
  - name: Gioia News
    url: https://gioia.news
    icon: https://raw.githubusercontent.com/LemmyNet/lemmy-ui/main/src/assets/icons/icon-96x96.png
  - name: Gioia Git
    url: https://git.gioia.cloud/
    expectedStatusCodes:
      - 200
      - 0

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gioia.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  introTitle: "Status page and uptime monitor for our self-hosted services"
  introMessage: "Monitor the status and uptime of our self-hosted services, powered by [Upptime](https://github.com/upptime/upptime)!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
